updated readme
old documentation :
  // {
  //   queries: string[];
  //   responses: Response[];
  // }
  // queries is an array of question strings
  // responses is an array of following structure:
  // {
  //   response: string;
  //   context?: string;
  // }
If we run a code according to this method mentioned, the code gave an error like 
----
Uncaught (in promise) TypeError: e.normalize is not a function
    at universal-sentence-encoder:formatted:77
    at c.encode (universal-sentence-encoder:formatted:79)
    at universal-sentence-encoder:formatted:173
    at Array.map (<anonymous>)
    at j.tokenizeStrings (universal-sentence-encoder:formatted:173)
    at universal-sentence-encoder:formatted:153
    at tfjs:formatted:9044
    at e.t.scopedRun (tfjs:formatted:9053)
    at e.t.tidy (tfjs:formatted:9037)
    at Object.bx [as tidy] (tfjs:formatted:12754)
----

The error exists in  Array that we pass
If we examine the code we see that 
---- universal-sentence-encoder
embed(e) {
            const n = t.tidy(()=>{
                const t = this.tokenizeStrings(e.queries, f)
                  , n = this.tokenizeStrings(e.responses, f);
                if (null != e.contexts && e.contexts.length !== e.responses.length)
                    throw new Error("The length of response strings and context strings need to match.");
                const o = e.contexts || [];
                null == e.contexts && (o.length = e.responses.length,
----

Here we see that e.queries , e.contexts so definitely both are properties of e.
So definitely 
- "responses" is not an array comprising response and context.

Correct code:
{  
queries:string[],
responses:string[],
contexts:string[]
}

"Context" is a completely separate Array of strings.